### ISSUE TITLE
is it possible to get snapshot file name in MediaPlayerSnapshotTaken event ? 

### ISSUE THREAD

**Issue by c1ngular** [adrg/libvlc-go#102]
or anyway to specify snapshot file name ? 
thanks

**Comment by adrg** [comment]
Hi @c1ngular,

Sorry for the late response. You should be able to specify the file name when using `Player.TakeSnapshot` in the `outputhPath` parameter. The function support only `PNG` snapshots.

```
player.TakeSnapshot("someDirectory/someFilename.png", 0, 0)
```

**Comment by c1ngular** [comment]
@adrg no problem at all， thank you
