### ISSUE TITLE
Cannot build basic player example

### ISSUE THREAD

**Issue by stevstrong** [adrg/libvlc-go#105]
Hi,

as also posted [here](https://github.com/adrg/libvlc-go-examples/issues/4), the build command for [basic player example](https://github.com/adrg/libvlc-go-examples/blob/master/v3/player/player.go) outputs on Win10 and Debian 11:
```
# command-line-arguments
.\player.go:12:16: undefined: vlc.Init
.\player.go:15:12: undefined: vlc.Release
.\player.go:18:21: undefined: vlc.NewPlayer
```
Any idea what I am missing?

**Comment by adrg** [comment]
Hi @stevstrong,

It looks like you don't have the `libvlc-go` package locally. It's as if you don't have a Go module for your project.

Go to the directory with the source code.
```go
go mod init main
go mod tidy
```

Then you should be able to build the project.
```go
go build
./main
```

**Comment by stevstrong** [comment]
Thanks, sorry for the late reply, but it is still not ok.

What I did:
- deleted existing mod file
- `go mod init player.go` (this is the name of the file)

reply:
```
go: to add module requirements and sums:
        go mod tidy
```
- `go mod tidy`

reply:
```
go: finding module for package github.com/adrg/libvlc-go/v3
go: found github.com/adrg/libvlc-go/v3 in github.com/adrg/libvlc-go/v3 v3.1.5
```

At this point this is the content of the `go.mod` file:
```
module player.go

go 1.20

require github.com/adrg/libvlc-go/v3 v3.1.5
```

Then:

- `go build player.go`

reply:
```
# command-line-arguments
.\player.go:12:16: undefined: vlc.Init
.\player.go:15:12: undefined: vlc.Release
.\player.go:18:21: undefined: vlc.NewPlayer
```

I think I am still missing something

**Comment by adrg** [comment]
> go mod init player.go (this is the name of the file)

You should not call the module the same as your file because the name of the executable generated after build will be called that as well and it will effectively replace your source file. The name of the module can be anything (`player`, `main`, etc.).

I think you mentioned you tried building on `Linux` as well. I just updated my `go` version to `1.20` to match yours and made a quick test. This works assuming you have `curl` and `libvlc-dev` installed (I'm on `Ubuntu` for reference).

Here are the exact steps:
```bash
mkdir player
cd player
curl "https://raw.githubusercontent.com/adrg/libvlc-go-examples/master/v3/player/player.go" -o main.go
go mod tidy
go build
./main
```

Assuming this worked, the project can be moved exactly as is on `Windows` and it should work there as well.

**Comment by stevstrong** [comment]
does the path where the source code is compared to GOPATH matter?

**Comment by adrg** [comment]
I'm not sure. There must be something weird going on with your setup. Can you post the output of `go env` from your `Linux` machine here?

One thing I noticed from your `Windows` environment is that the `CGO_ENABLED` environment variable is set to `0`. It should be set to `1`. You could try that and attempt building the project again.

**Comment by stevstrong** [comment]
I did on Windows:

`go env -w CGO_ENABLED=1`

and retried build with this output:
```
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
```

**Comment by stevstrong** [comment]
Ah, I somehow overlooked this step on Win. I will try it and post here the result.

I also have to look why it does not work on Linux, I think the prerequisites were loaded there already.

**Comment by stevstrong** [comment]
I acknowledge, on Linux the `CGO_ENABLED` flag was also set to `0`.
I think this flag is set at install time because GCC was not recognized (not installed). Maybe because I have there a minimal Debian installation.

After I ran:
`sudo apt-get install build-essential`
the build worked like a charm!

Maybe it makes sense to extend the read.me with this information to help other users like me.
Thanks anyway for the support and the great work!
