### ISSUE TITLE
Build problem on Mac

### ISSUE THREAD

**Issue by nkalait** [adrg/libvlc-go#113]
On mac Sonoma 14.4.1 when trying to build the usage example on the readMe, I get the error(s) below:

```
# github.com/adrg/libvlc-go/v3
../../../go/pkg/mod/github.com/adrg/libvlc-go/v3@v3.1.5/event_manager.go:10:40: error: incompatible function pointer types passing 'void (libvlc_event_t *, void *)' (aka 'void (struct libvlc_event_t *, void *)') to parameter of type 'libvlc_callback_t' (aka 'void (*)(const struct libvlc_event_t *, void *)') [-Wincompatible-function-pointer-types]
    return libvlc_event_attach(em, et, eventDispatch, (void*)userData);
                                       ^~~~~~~~~~~~~
/usr/local/include/vlc/libvlc.h:339:59: note: passing argument to parameter 'f_callback' here
                                        libvlc_callback_t f_callback,
                                                          ^
../../../go/pkg/mod/github.com/adrg/libvlc-go/v3@v3.1.5/event_manager.go:13:33: error: incompatible function pointer types passing 'void (libvlc_event_t *, void *)' (aka 'void (struct libvlc_event_t *, void *)') to parameter of type 'libvlc_callback_t' (aka 'void (*)(const struct libvlc_event_t *, void *)') [-Wincompatible-function-pointer-types]
    libvlc_event_detach(em, et, eventDispatch, (void*)userData);
                                ^~~~~~~~~~~~~
/usr/local/include/vlc/libvlc.h:352:60: note: passing argument to parameter 'f_callback' here
                                         libvlc_callback_t f_callback,
                                                           ^
2 errors generated.
```

I have followed the instructions in https://github.com/adrg/libvlc-go/wiki/Install-on-macOS

my clang version:
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0

**Comment by nkalait** [comment]
After some searching I gathered that it is a problem with the default compiler on my Mac. 

The solution was to install gcc using Homebrew:
`brew install gcc`

Then build or run the code using the newly installed Homebrew compiler:
`CC=gcc-13 go run .`
`CC=gcc-13 go build`

But it seems the Homebrew compiler uses different include paths and not really understanding how the c compiler works I just placed links in the folders that it uses by default:
```
sudo ln -s /Applications/VLC.app/Contents/MacOS/include/vlc /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc/x86_64-apple-darwin23/13/include/
sudo ln -s /Applications/MacPorts/VLC.app/Contents/MacOS/lib/* /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/
```

After all these changes I was able to run the code using the command below.
`CC=gcc-13 go run .`

The exact Homebrew gcc:
gcc-13 (Homebrew GCC 13.2.0) 13.2.0

**Comment by GwynethLlewelyn** [comment]
Hmm. The Apple `clang` compiler should also work fine. The trick is just letting Go know where the extra files/libraries are. Note that under your proposed solution, every time `gcc` changes, or VLC, or, well, `libvlc-go`, you need to have to redo everything from scratch — breaking the symlinks, creating new ones, making sure you're calling the correct version of `gcc` (and that it has everything needed at hand!), and so forth.

Instead, see my comments on issues #113 and #116 — there is a far easier and future-proof way of telling the `cgo` subsystem where to find the VLC header files and libraries.
