### ISSUE TITLE
osx library not found, but installed

### ISSUE THREAD

**Issue by virskor** [adrg/libvlc-go#12]
ld: library not found for -lvlc
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by adrg** [comment]
Can someone using the library on OS X help with this issue?

**Comment by gaurav-gogia** [comment]
I had similar error so something like this should work:

1. Make sure MacOSX.sdk exists by using following command
`ls SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`

2. If its there then cool go for next command
`export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`

If its not there then you'll need to install xcode-command-line-tools

I hope this helps

**Comment by adrg** [comment]
Closing this issue. Let's discuss all macOS installation issues in https://github.com/adrg/libvlc-go/issues/13.
