### ISSUE TITLE
Media list player ignores --fullscreen command line argument.

### ISSUE THREAD

**Issue by danielpellon** [adrg/libvlc-go#14]
I am trying to write a program that plays a playlist in fullscreen mode.

Given that Media list player does not have the function SetFullScreen as opposed to Media Player, I have tried to achieve this by using the --fullscreen argument on the Init function, however the videos still start in windowed mode. (--fullscreen argument also works fine with normal player)

I have also tried to manually set fullscreen mode to be always on on vlc player preferences with no success.

Here is my code, which is almost the same as the example code for this library.

```
package main

import (
	"log"
	"time"

	vlc "github.com/adrg/libvlc-go"
)

func main() {
	// Initialize libvlc. Additional command line arguments can be passed in
	// to libvlc by specifying them in the Init function.
	if err := vlc.Init("--fullscreen"); err != nil {
		log.Fatal(err)
	}
	defer vlc.Release()

	// Create a new list player
	player, err := vlc.NewListPlayer()
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		player.Stop()
		player.Release()
	}()

	//player.SetPlaybackMode()
	// Create a new media list
	list, err := vlc.NewMediaList()
	if err != nil {
		log.Fatal(err)
	}
	defer list.Release()

	err = list.AddMediaFromPath("video2.mp4")
	if err != nil {
		log.Fatal(err)
	}

	err = list.AddMediaFromPath("video1.mp4")
	if err != nil {
		log.Fatal(err)
	}

	// Set player media list
	err = player.SetMediaList(list)
	if err != nil {
		log.Fatal(err)
	}

	// Play
	err = player.Play()
	if err != nil {
		log.Fatal(err)
	}

	time.Sleep(60 * 1000 * time.Millisecond)
}
```
I am running the latest version of vlc 3.0.4 and the latest version of this library on arch linux.

**Comment by adrg** [comment]
@danielpellon Thank you for reporting the issue. I did not add a SetFullscreen to the list player because libvlc itself does not have this method for the list player.

However, the list player does have an underlying regular player. Once I retrieve that, I can implement all methods specific to the regular player on the list player.

I will give you a mention once I implement the new methods.
