### ISSUE TITLE
Adding support for events

### ISSUE THREAD

**Issue by patknight** [adrg/libvlc-go#18]
I want to add support for VLC events in my app. I see there's a two year old branch where work was started. Should I work in that branch, or should I start from scratch with a branch from head of master? What's your preference - I'm happy either way?

**Comment by adrg** [comment]
Hi @patknight,

I think it's best that you create a new branch starting from master and cherry-pick the useful code from the events branch. 

I already added the event types at some point but did not get to adding the event logic.
https://github.com/adrg/libvlc-go/blob/master/events.go

**Comment by patknight** [comment]
Hi @adrg,

That's what I thought, but it's your code base so I wanted to ask. My initial thought is to leave events.go alone as a place for the types and constants, and put the implementation in another file. Does that make sense?

**Comment by adrg** [comment]
Sure. We should leave events.go as is. Not sure if it's the most appropriate file name, but it's good enough for now.

**Comment by adrg** [comment]
Event management added in PR https://github.com/adrg/libvlc-go/pull/20
