### ISSUE TITLE
provide example for opengl

### ISSUE THREAD

**Issue by sk8245** [adrg/libvlc-go#21]
hi,
is it possible to add an example of how to use this with opengl in golang? I just wanna render a video (with sound) in an openGL window.
thanks

**Comment by adrg** [comment]
@sk8245 Do you want to render video to a texture? If so, libVLC v3 does not support this. I know there's some development regarding this in v4, but v4 is in development. I will add bindings when there's a stable version of v4 as the API will likely change.

If you simply want to render a video in a window, I've added a GTK player example which renders  video to a gtk.DrawingArea: https://github.com/adrg/libvlc-go/blob/master/v3/examples/gtk_player.go

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if the provided solution is not suitable for your use case.
