### ISSUE TITLE
Player.Stop() function not return

### ISSUE THREAD

**Issue by fovecifer** [adrg/libvlc-go#24]
I am using libvlc-go to play HLS stream, and found sometimes Player.Stop() blocked, and no return, it seems like the problem of libvlc libvlc_media_player_stop.

the golang code is simple, there is no chance to block, am I right?

**Comment by adrg** [comment]
Hi @fovecifer. Yes, most likely some issue with libvlc_media_player_stop. 
Could you post a sample of your code so I can make some tests?

**Comment by fovecifer** [comment]
I just copy the code from README Player usage, and I do not using "defer".
and the streams which has problem all from same CDN, thanks for your help, but I could not share the streams out of company.
I will do more tests, maybe I should make an issue in libvlc, not here.
