### ISSUE TITLE
github.com\adrg\libvlc-go\audio.go:4:11: fatal error: vlc/vlc.h: No such file or directory

### ISSUE THREAD

**Issue by sriteja1993** [adrg/libvlc-go#25]
I am trying do go get github.com/adrg/libvlc-go , i am getting this error in windows environment.Can any one explain the steps and required dependencies  for windows environment.

Below is the issue i am getting.

vlc player version:3.0.8
Gcc version:8.1.0
Os windows10

github.com\adrg\libvlc-go\audio.go:4:11: fatal error: vlc/vlc.h: No such file or directory
 // #include <vlc/vlc.h>
           ^~~~~~~~~~~
compilation terminated.

**Comment by adrg** [comment]
Hi @sriteja1993. Thank you for your interest in the library. I will test the package on Windows over the weekend and add specific installation and usage instructions.

**Comment by adrg** [comment]
@sriteja1993 I've added a wiki page with instructions on how to build the package on Windows:
[https://github.com/adrg/libvlc-go/wiki/Install-on-Windows](https://github.com/adrg/libvlc-go/wiki/Install-on-Windows)

**Comment by sriteja1993** [comment]
@adrg Thanks it's working.

**Comment by adrg** [comment]
Glad to hear it's working for you! :)
