### ISSUE TITLE
module not initialized error

### ISSUE THREAD

**Issue by bakurits** [adrg/libvlc-go#27]
I'm trying to run example code in my Ubuntu 18.04 machine, with Golang 1.13

I'm getting a random **module not initialized** for every operation.

```go
if err := vlc.Init(); err != nil {
	log.Fatal(err)
}
```
In here `err` is nil but when I debugged 
```go
handle := C.libvlc_new(C.int(argc), *(***C.char)(unsafe.Pointer(&argv)))
if handle == nil {
	return getError()
}
```
`handle` is `nil` but `getError()` also returning `nil`. How can I resolve this?

**Comment by adrg** [comment]
Hi @bakurits. That usually happens when libvlc.so is not loaded sucessfully. 
How did you install `libvlc-dev`? I also use Ubuntu 18.04 and it's working ok for me. I installed it using apt: `sudo apt-get install libvlc-dev`.

**Comment by bakurits** [comment]
> Hi @bakurits. That usually happens when libvlc.so is not loaded sucessfully.
> How did you install `libvlc-dev`? I also use Ubuntu 18.04 and it's working ok for me. I installed it using apt: `sudo apt-get install libvlc-dev`.

I have installed it the same way. I tried reinstalling. When I deleted `libvlc-dev` this error occured
![Screenshot from 2020-02-14 10-15-23](https://user-images.githubusercontent.com/10448754/74506511-3c212700-4f13-11ea-854f-e565c505c1bf.png)
after installing it with `sudo apt-get install libvlc-dev` there is same `module not initialized` error

**Comment by adrg** [comment]
Hm, that's weird. Could try initializing the library with the `-vvv` flag?
```go
vlc.Init("--no-video", "-vvv")`
```
Maybe there is some output there pointing to the issue.

**Comment by bakurits** [comment]
> Hm, that's weird. Could try initializing the library with the `-vvv` flag?
> 
> ```go
> vlc.Init("--no-video", "-vvv")
> ```
> 
> Maybe there is some output there pointing to the issue.
> Also you could try installing the `vlc` package along with `libvlc-dev`: `sudo apt-get install vlc`.
> 
> EDIT: I managed to reproduce the issue. Seems like the bare minimum needed to run is `libvlc-dev` and `vlc-plugin-base`. Installing the `vlc` package also works, but it installs much more than that.
> 
> So:
> 
> ```shell
> sudo apt-get install libvlc-dev
> sudo apt-get install vlc-plugin-base
> ```
> 
> Let me know if that works for you.

It works. Now I only get audio output, but I guess it's another issue. I'll try some tinkering and let you know

**Comment by adrg** [comment]
If you don't pass the `--no-video` argument to the `Init` method, you should also get video. In any case, using the `-vvv` argument should give some clue regarding issues.

**Comment by adrg** [comment]
Also try installing the `vlc-plugin-video-output` plugin and check if that solves your issue.

**Comment by bakurits** [comment]
> Also try installing the `vlc-plugin-video-output` plugin and check if that solves your issue.

Everything works fine now. Thanks

**Comment by adrg** [comment]
No problem. Glad to help.
