### ISSUE TITLE
Get Media Stats

### ISSUE THREAD

**Issue by nithinkashyapn** [adrg/libvlc-go#29]
Hey,

How do I obtain the stats for a video which is being played using `libvlc-go`? 

Thanks

**Comment by adrg** [comment]
Hi @nithinkashyapn. Thank you for your interest in the library. I assume you are referring to the [libvlc_media_get_stats](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media.html#ga9057ada11e176f4e2b5b5f529edad076) binding? If so, it's not implemented yet. However, it seems like an useful addition to the library so I will add it some time this week and let you know.

**Comment by nithinkashyapn** [comment]
Hey @adrg Thanks for the support! Looking forward to it.

**Comment by adrg** [comment]
@nithinkashyapn I added the new binding for getting media playback statistics. I also added an example for it: https://github.com/adrg/libvlc-go/blob/master/examples/event_handling.go.

**Comment by nithinkashyapn** [comment]
Hey @adrg, Thanks for the solution and example. Will use it right away :)
