### ISSUE TITLE
MediaTime() returns seconds instead of milliseconds.

### ISSUE THREAD

**Issue by polypmer** [adrg/libvlc-go#4]
I've been using player.MediaTime() to get milliseconds, and it's now returning seconds instead of milliseconds. So either the documentation is wrong, or something funny is going on.

https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#ga1a5ccaa2c044ded47205cd0754f68370

That's where it says it ought to be milliseconds, and unless I'm remembering incorrectly, this method was returning milliseconds for me a few days ago.

**Comment by polypmer** [comment]
No, I think I'm doing something wrong on my end. I guess I'll reopen this if I can figure it out.

**Comment by polypmer** [comment]
yeah, no cause for alarm....

**Comment by adrg** [comment]
Glad you've solved the problem. :)
