### ISSUE TITLE
Error messages when trying to run

### ISSUE THREAD

**Issue by ericsartor** [adrg/libvlc-go#40]
I copied the code for the "Basic player usage" example, and used my own local video file.  I'm getting the below errors when I try to run or build.  I'm not familiar with C, but it seems it's complaining about something in the C code...

```
$ go run video

\# github.com/adrg/libvlc-go/v2

In file included from _cgo_export.c:4:

event_manager.go: In function 'eventAttach':

event_manager.go:11:55: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]

event_manager.go: In function 'eventDetach':

event_manager.go:14:48: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]

\# github.com/adrg/libvlc-go/v2

..\github.com\adrg\libvlc-go\v2\event_manager.go: In function 'eventAttach':

..\github.com\adrg\libvlc-go\v2\event_manager.go:11:55: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]

   11 |     return libvlc_event_attach(em, et, eventDispatch, (void*)userData);

      |                                                       ^

..\github.com\adrg\libvlc-go\v2\event_manager.go: In function 'eventDetach':

..\github.com\adrg\libvlc-go\v2\event_manager.go:14:48: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]

   14 |     libvlc_event_detach(em, et, eventDispatch, (void*)userData);

      |                                                ^

\# github.com/adrg/libvlc-go/v2

cgo-gcc-prolog: In function '_cgo_7b301a7633e1_Cfunc_libvlc_media_is_parsed':

cgo-gcc-prolog:154:2: warning: 'libvlc_media_is_parsed' is deprecated [-Wdeprecated-declarations]

In file included from C:\libvlc\include/vlc/vlc.h:51,

                 from ..\github.com\adrg\libvlc-go\v2\media.go:4:

C:\libvlc\include/vlc/deprecated.h:249:4: note: declared here

  249 |    libvlc_media_is_parsed( libvlc_media_t *p_md );

      |    ^~~~~~~~~~~~~~~~~~~~~~

cgo-gcc-prolog: In function '_cgo_7b301a7633e1_Cfunc_libvlc_media_parse':

cgo-gcc-prolog:207:2: warning: 'libvlc_media_parse' is deprecated [-Wdeprecated-declarations]

In file included from C:\libvlc\include/vlc/vlc.h:51,

                 from ..\github.com\adrg\libvlc-go\v2\media.go:4:

C:\libvlc\include/vlc/deprecated.h:209:1: note: declared here

  209 | libvlc_media_parse( libvlc_media_t *p_md );

      | ^~~~~~~~~~~~~~~~~~

cgo-gcc-prolog: In function '_cgo_7b301a7633e1_Cfunc_libvlc_media_parse_async':

cgo-gcc-prolog:219:2: warning: 'libvlc_media_parse_async' is deprecated [-Wdeprecated-declarations]

In file included from C:\libvlc\include/vlc/vlc.h:51,

                 from ..\github.com\adrg\libvlc-go\v2\media.go:4:

C:\libvlc\include/vlc/deprecated.h:233:1: note: declared here

  233 | libvlc_media_parse_async( libvlc_media_t *p_md );

      | ^~~~~~~~~~~~~~~~~~~~~~~~

exit status 3221225781

```

**Comment by ericsartor** [comment]
I'm on Windows 10 64-bit, forgot to mention that!

**Comment by ericsartor** [comment]
And using v3 of the library.

**Comment by adrg** [comment]
Hi @ericsartor. How did you install libvlc? Did you follow the installation guide on the [wiki page](https://github.com/adrg/libvlc-go/wiki/Install-on-Windows)? 
Could you do `gcc --version` in Windows CMD and copy the output here? Also, what version of go are you running?

I don't see anything pointing to the issue in the output you provided. There are some deprecation notices for some of the bindings, which should not really cause any problems. libVLC still supports those bindings in v3, so I must support them as well. 
The only other thing is `exit status 3221225781`, which usually means that it's missing a dependency, but the exit code is somewhat generic so I cannot be sure.

If you want to suppress the deprecation notices, you can do: 
```
set CGO_CFLAGS=-IC:\libvlc\include -D LIBSOLV_INTERNAL -w
set CGO_LDFLAGS=-LC:\libvlc
go build
```

Also, from the output you copied, it seems you are using the `v2` package version: `github.com/adrg/libvlc-go/v2` instead of `github.com/adrg/libvlc-go/v3`. However, that should not be an issue. Just something I noticed.

**Comment by ericsartor** [comment]
I followed the installation guide, but after doing that, I still needed to install gcc (I was getting errors).   i found something online that pointed to a particular installer so I installed that.  This is what I get from `gcc --verison`:

```
gcc (tdm64-1) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I *was* using v3, but I think I tried using v2 as a debugging step and forgot to change it back before I copied my code.

I'm relatively new to Go, sorry for my lack of familiarity :)

**Comment by ericsartor** [comment]
`go version go1.14 windows/amd64`

**Comment by adrg** [comment]
I added a [wiki page](https://github.com/adrg/libvlc-go/wiki/Install-MinGW-toolchain) for installing the `MinGW` toolchain. Make sure you uninstall your current compiler first. I also updated the [Install on Windows](https://github.com/adrg/libvlc-go/wiki/Install-on-Windows) wiki page to include this section.

If you want to build the GTK 3 examples, follow the installation instructions on the [Build GTK 3 examples](https://github.com/adrg/libvlc-go/wiki/Build-GTK-3-examples) wiki page, as it showcases how to install all dependencies, including `MinGW`. Similarly, if you want to build the GTK 2 examples, follow the instructions on the [Build GTK 2 examples](https://github.com/adrg/libvlc-go/wiki/Build-GTK-2-examples) wiki page.

Let me know if you encounter any issues.

**Comment by bakurits** [comment]
@adrg same here with ubuntu 
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**Comment by adrg** [comment]
Hi @bakurits. Did you follow the Linux installation instructions on the [wiki page](https://github.com/adrg/libvlc-go/wiki/Install-on-Linux)? If so, what errors are you receiving?

**Comment by bakurits** [comment]
Yes I have this is what I'm getting 
```
# github.com/adrg/libvlc-go/v3
cgo-gcc-prolog: In function ‘_cgo_c7c856de85d4_Cfunc_libvlc_media_is_parsed’:
cgo-gcc-prolog:173:2: warning: ‘libvlc_media_is_parsed’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/vlc/vlc.h:51,
                 from ../../../go/pkg/mod/github.com/adrg/libvlc-go/v3@v3.0.3/media.go:4:
/usr/include/vlc/deprecated.h:249:4: note: declared here
  249 |    libvlc_media_is_parsed( libvlc_media_t *p_md );
      |    ^~~~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function ‘_cgo_c7c856de85d4_Cfunc_libvlc_media_parse’:
cgo-gcc-prolog:226:2: warning: ‘libvlc_media_parse’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/vlc/vlc.h:51,
                 from ../../../go/pkg/mod/github.com/adrg/libvlc-go/v3@v3.0.3/media.go:4:
/usr/include/vlc/deprecated.h:209:1: note: declared here
  209 | libvlc_media_parse( libvlc_media_t *p_md );
      | ^~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function ‘_cgo_c7c856de85d4_Cfunc_libvlc_media_parse_async’:
cgo-gcc-prolog:238:2: warning: ‘libvlc_media_parse_async’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/vlc/vlc.h:51,
                 from ../../../go/pkg/mod/github.com/adrg/libvlc-go/v3@v3.0.3/media.go:4:
/usr/include/vlc/deprecated.h:233:1: note: declared here
  233 | libvlc_media_parse_async( libvlc_media_t *p_md );
      | ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by adrg** [comment]
Those are just some deprecation warnings for some functions libVLC still supports in v3, so this package supports them as well. Is your binary built?

If you don't want to see those try doing:
```
CGO_CFLAGS="-Wno-deprecated-declarations" go build
```
or
```
CGO_CFLAGS="-w" go build
```

**Comment by adrg** [comment]
@ericsartor Did you get the chance to try the instructions provided in my latest comment regarding the MinGW toolchain? Did they work for you as well? If so, can this issue be closed?
@bakurits Can this issue be closed?

**Comment by bakurits** [comment]
I resolved warnings with your help, so green light from me

**Comment by adrg** [comment]
@bakurits Great to hear. I think I will suppress those warnings from within the library on the next release so that building process is easier.

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if there are any issues with the provided solution.
