### ISSUE TITLE
Reading video from UDP stream

### ISSUE THREAD

**Issue by MikolajMGT** [adrg/libvlc-go#42]
Hello there!
Is it possible to read video from UDP stream using this library? VLC itself provides option to run from commandline e.g. `vlc udp://@:25565` which allow to play video stream. I am during development of client-server app and it would be nice if I could embed vlc player (as in example app) which handles UDP stream :)
Regards

**Comment by adrg** [comment]
Hi @MikolajMGT. Yes, reading UDP video streams is possible. I made a quick test by streaming a video using `cvlc` and reading it using the [player example](https://github.com/adrg/libvlc-go/blob/master/v3/examples/player.go), by passing the type of URL you mentioned to the player's `LoadMediaFromURL` method.
 
**Stream**
```bash
cvlc video.mp4 --sout '#transcode{vcodec=h264}:std{access=udp,mux=ts,dst=127.0.0.1:10000}'
```

**Read**
```go
package main

import (
	"log"

	vlc "github.com/adrg/libvlc-go/v3"
)

func main() {
	if err := vlc.Init("--quiet"); err != nil {
		log.Fatal(err)
	}
	defer vlc.Release()

	player, err := vlc.NewPlayer()
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		player.Stop()
		player.Release()
	}()

	media, err := player.LoadMediaFromURL("udp://@:10000")
	if err != nil {
		log.Fatal(err)
	}
	defer media.Release()

	err = player.Play()
	if err != nil {
		log.Fatal(err)
	}

	manager, err := player.EventManager()
	if err != nil {
		log.Fatal(err)
	}

	quit := make(chan struct{})
	eventCallback := func(event vlc.Event, userData interface{}) {
		close(quit)
	}

	eventID, err := manager.Attach(vlc.MediaPlayerEndReached, eventCallback, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer manager.Detach(eventID)

	<-quit
}
```

**Comment by MikolajMGT** [comment]
Awesome, thanks for example :)
