### ISSUE TITLE
painful audio quality

### ISSUE THREAD

**Issue by belikesayantan** [adrg/libvlc-go#51]
# improve the playback audio quality

i tried the following code: 
```
package main

import (
	"log"

	vlc "github.com/adrg/libvlc-go/v3"
)

// CGO_CFLAGS="-w" go build .
func main() {
	// Initialize libVLC. Additional command line arguments can be passed in
	// to libVLC by specifying them in the Init function.
	if err := vlc.Init("--no-video", "--quiet"); err != nil {
		log.Fatal(err)
	}
	defer vlc.Release()

	// Create a new player.
	player, err := vlc.NewPlayer()
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		player.Stop()
		player.Release()
	}()

	// Add a media file from path or from URL.
	// Set player media from path:
	// media, err := player.LoadMediaFromPath("localpath/test.mp4")
	// Set player media from URL:
	media, err := player.LoadMediaFromURL("https://r5---sn-gwpa-gq2e.googlevideo.com/videoplayback?expire=1593434953&ei=6Y75XpuVNIKcogPr0J7oDw&ip=47.15.50.228&id=o-ADIDnqw9I6KxlrHhjiZ5uGu0iug228_DIthefGwcIg8_&itag=251&source=youtube&requiressl=yes&mh=Sn&mm=31%2C29&mn=sn-gwpa-gq2e%2Csn-qxaeen7e&ms=au%2Crdu&mv=m&mvi=4&pl=19&gcr=in&initcwndbps=123750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4605080&dur=281.521&lmt=1584770159942304&mt=1593413256&fvip=5&keepalive=yes&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgMeTID1UXd8RsEHQn01UhMNVRDjCGuhi8vvP-oLYJuzUCIQD30d9R1M4oa-dZoYWs_xvYddna9_RTcqICCBaOR0wVqg%3D%3D&sig=AOq0QJ8wRQIhAKe6xdTewTAddBGHWBwe82_gUrwMwk-LWfa7IgRw7pmRAiBAbqehNIFD6DI4--0j0OjLJtGYVo8oJtQEZ4M5Acku1g==&ratebypass=yes")
	if err != nil {
		log.Fatal(err)
	}
	defer media.Release()

	// Start playing the media.
	err = player.Play()
	if err != nil {
		log.Fatal(err)
	}

	// Retrieve player event manager.
	manager, err := player.EventManager()
	if err != nil {
		log.Fatal(err)
	}

	// Register the media end reached event with the event manager.
	quit := make(chan struct{})
	eventCallback := func(event vlc.Event, userData interface{}) {
		close(quit)
	}

	eventID, err := manager.Attach(vlc.MediaPlayerEndReached, eventCallback, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer manager.Detach(eventID)

	<-quit
}

```

you can play the [url](https://r5---sn-gwpa-gq2e.googlevideo.com/videoplayback?expire=1593434953&ei=6Y75XpuVNIKcogPr0J7oDw&ip=47.15.50.228&id=o-ADIDnqw9I6KxlrHhjiZ5uGu0iug228_DIthefGwcIg8_&itag=251&source=youtube&requiressl=yes&mh=Sn&mm=31%2C29&mn=sn-gwpa-gq2e%2Csn-qxaeen7e&ms=au%2Crdu&mv=m&mvi=4&pl=19&gcr=in&initcwndbps=123750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4605080&dur=281.521&lmt=1584770159942304&mt=1593413256&fvip=5&keepalive=yes&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgMeTID1UXd8RsEHQn01UhMNVRDjCGuhi8vvP-oLYJuzUCIQD30d9R1M4oa-dZoYWs_xvYddna9_RTcqICCBaOR0wVqg%3D%3D&sig=AOq0QJ8wRQIhAKe6xdTewTAddBGHWBwe82_gUrwMwk-LWfa7IgRw7pmRAiBAbqehNIFD6DI4--0j0OjLJtGYVo8oJtQEZ4M5Acku1g==&ratebypass=yes) in web browser and understand what i mean.

**Comment by adrg** [comment]
Hi @belikesayantan.

Thanks for opening the issue. I think there's a permission problem with the video file you mentioned. I get an authorization error when trying to access it in the browser:  `You don't have authorization to view this page.`.

**Comment by belikesayantan** [comment]
@adrg sorry about that, 

actually I accessed that url using youtube-dl.

after installing youtube-dl, if u run a command:

```youtube-dl -g -x kJQP7kiw5Fk```

Actually, libvlc can't render the beats and bass in the audio

**Comment by adrg** [comment]
You can use a list player instead of a regular player to play the `Youtube` video directly, without going through `youtube-dl` first.
You can use the regular player as well, although there are a couple of extra steps involved.
Could you try the examples in issue https://github.com/adrg/libvlc-go/issues/47 and see if the problem persists?

**Comment by belikesayantan** [comment]
ok thanks, that works too !
