### ISSUE TITLE
examples on playback features of libvlc-go

### ISSUE THREAD

**Issue by belikesayantan** [adrg/libvlc-go#52]
@adrg, libvlc-go is an awesome audio-video bindings in golang and is playing a keyrole in my project, i.e, a music player.
can you provide any example of how to add certain playback features such as play/pause forward/backward that can be invoked on certain keystrokes.

**Comment by adrg** [comment]
@belikesayantan. Is it a CLI music player? What package are you using for catching key presses?
The `Player` struct has methods for the actions you mentioned like `Play`, `Stop`, `SetPause`, `SetMediaTime`, `SetMediaPosition`.
You can find the method reference at https://pkg.go.dev/github.com/adrg/libvlc-go/v3.

**Comment by belikesayantan** [comment]
i am using [termui](https://github.com/gizak/termui/) for catching the key presses. actually i solved that issue, thanks
