### ISSUE TITLE
Why Ebedded  VLC on Microsoft Windows,  background  is transparent.

### ISSUE THREAD

**Issue by gallex** [adrg/libvlc-go#55]
I wrote a program under Microsoft Windows ,  which embed a LVC in a GTK DrawingArea .  It seems OK  except that the background  around video (the gap between video and others)   is transparent. 

I'v connect draw event to a function  and use cr.SetSourceRGB(0, 255, 0)/cr.Paint() to draw background. When I click to maximize window,  sometimes I can see the green  background ,  but at  most time it keep transparent.

BTW: same program is All OK under linux

**Comment by gallex** [comment]
```
func main() {

	// Initialize libVLC module.
	err := vlc.Init("--quiet", "--no-xlib")
	assertErr(err)
	
	gtk.Init(nil)

	Window, _ = gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	hPanel, _ = gtk.BoxNew(gtk.ORIENTATION_HORIZONTAL, 0)
	
	playerArea, _ = gtk.DrawingAreaNew()
	hPanel.PackEnd(playerArea, true, true, 0)

	Window.SetTitle("销售终端")
	Window.SetDefaultSize(1024, 768)
	Window.Connect("destroy", gtk.MainQuit)

	playerArea.Connect("draw", func(playerArea *gtk.DrawingArea, cr *cairo.Context) {
		cr.SetSourceRGB(0, 0, 0)
		cr.Paint()
	})
	
	// Create a new player.
	player, err := vlc.NewPlayer()
	if err != nil {
		log.Println("Cant' Attach video player", err);
		return
	}
	
	_, err = player.LoadMediaFromPath("..\\selpos\\install\\videos\\11111-0-0-11111.mp4")
	if err != nil {
		log.Println("Cant' load video", err);
		return
	}
	
	playerArea.Connect("realize", func(playerArea *gtk.DrawingArea) {
				fmt.Println("realize");
				// Set window for the player.
				playerWindow, err := playerArea.GetWindow()
				assertErr(err)
				setPlayerWindow(player, playerWindow)
				assertErr(err)
				player.Play()
	})
	
	Window.Add(hPanel)
	Window.ShowAll()
	
	gtk.Main()
	
}
```

**Comment by gallex** [comment]
I found some hint : When I  add a GtkHeaderBar to the mainWindows It  would OK. Why?

**Comment by adrg** [comment]
Hi @gallex. I'm not sure what the issue is. Seems more like a GTK problem. You are right, the issue does not manifest with a custom GtkHeaderBar. I've noticed that setting `window.SetDecorated(false)` also solves the issue (although there's no title bar after that). I'm not sure how the default title bar (or decorations) affects the drawing area. It's as if it captures expose events and prevents them from getting passed to the drawing area.

I'll investigate this more and let you know.

**Comment by gallex** [comment]
@adrg thans for your reply. Fortunately, I can use your solution to solve my problem( I just do not need any title).

**Comment by gallex** [comment]
>  It's as if it captures expose events and prevents them from getting passed to the drawing area. I'll investigate this further and let you know.

I am sure  draw event is captured case I have print  logs in the  function .
