### ISSUE TITLE
where is the stream, track and codec information?

### ISSUE THREAD

**Issue by nergdron** [adrg/libvlc-go#58]
I'm just getting started with these bindings, but I'm not seeing obvious equivalents for some of the media info functionality in the upstream libvlc3. specifically, I want to identify all the codec and format information about all the tracks in a media container, but I don't see stuff that maps to `libvlc_media_get_codec_description()`, `i_codec` or `i_original_fourcc`. am I missing something? or are these just things that still need to be added to these bindings?

**Comment by adrg** [comment]
Hi @nergdron. Thank you for your interest in the library. The bindings for retrieving track and codec info are not implemented yet. 
I'll add them in couple of days, as they seem like useful additions.

**Comment by nergdron** [comment]
oh, rad, I'll look forward to that then! thanks!

**Comment by adrg** [comment]
Hi @nergdron. I added the bindings for retrieving media tracks and codec descriptions in v3.0.7.
I also added an example for them: https://github.com/adrg/libvlc-go-examples/blob/master/v3/media_tracks/media_tracks.go.

**Comment by nergdron** [comment]
awesome, I'll check those out soon, thanks so much!
