### ISSUE TITLE
Add bindings for renderer discoverer

### ISSUE THREAD

**Issue by mfkl** [adrg/libvlc-go#66]
A user asked for this on the LibVLC community discord. This would allow to find and stream to chromecasts on the local network.

https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__renderer__discoverer.html

**Comment by mfkl** [comment]
I see you have the events for it already

https://github.com/adrg/libvlc-go/blob/93f9c6defcde4bd3074498f080c4c17e06fd0ff9/v3/events.go#L120-L130

**Comment by adrg** [comment]
@mfkl Thank you for letting me know. I'll work on implementing the renderer discoverer set of bindings next. Hopefully, I'll release a new version with them early next week.

**Comment by adrg** [comment]
Hi @mfkl. The renderer discovery functionality has been added in [v3.1.0](https://github.com/adrg/libvlc-go/releases/tag/v3.1.0). I also added a stream media to Chromecast [example](https://github.com/adrg/libvlc-go-examples/blob/master/v3/chromecast_streaming/chromecast_streaming.go).
