### ISSUE TITLE
[question] Prevent gap between media

### ISSUE THREAD

**Issue by masseelch** [adrg/libvlc-go#76]
I try to load 2 videos after another without having a gap between them (the desktop is shown for a very short period of time). I tried with the `ListPlayer()` but it did not work.

My next idea was to pause at the last frame, make sure the next video is playing and then stop the current media. Hence [this question](https://github.com/adrg/libvlc-go/issues/75). However, this causes the flickering between the two videos until the first video is stopped.

Idea 3: Every 10ms check if the video 2 has `MediaTime() > 0` and stop video 1. I now have only 1 "Flicker-Frame". Still not what I want.

I do not know what to do next. Do you have an idea? How to prevent the gap between to videos? 

Videos are played on a Raspberry 4 with `--vout mmal_vout`.

**Comment by adrg** [comment]
Hi @masseelch. I don't think there's a good way to accomplish this in libVLC 3. I know that this feature is being worked on in libVLC 4, but that is not out yet. You can join the libVLC Discord server (there's a link badge in the README of this project) and ask there (the General channel is probably most appropriate) but as far as I know, this is not possible in the current version on libVLC.

**Comment by masseelch** [comment]
I'll try that, thank you!
