### ISSUE TITLE
[bug] Random error when detaching event

### ISSUE THREAD

**Issue by masseelch** [adrg/libvlc-go#77]
Detaching an event sometimes throws the following:

```
SIGABRT: abort
PC=0xb6dedf24 m=5 sigcode=4294967290

goroutine 0 [idle]:
runtime: unknown pc 0xb6dedf24
stack: frame={sp:0xa52feb08, fp:0x0} stack=[0xa4aff1a4,0xa52feda4)
a52fea88:  00000000  fde31900  00000000  92772680 
a52fea98:  00000000  fde31900  00000000  92772670 
a52feaa8:  00000000  fde31900  00000000  92772660 
a52feab8:  00000000  fde31900  00000000  92772650 
a52feac8:  00000000  fde31900  00000000  92772640 
a52fead8:  00000000  fde31900  00000000  92772630 
a52feae8:  00000000  00000006  00000109  a3f04080 
a52feaf8:  a3f0408c  a52feb8c  b6fc0968  b6dedea8 
a52feb08: <00000000  00000000  00000000  92772600 
a52feb18:  00000000  fde31900  00000000  000555c8 <runtime.findrunnable+2800> 
a52feb28:  01028060  00000000  00000000  927725e0 
a52feb38:  00055d50 <runtime.findrunnable+4728>  006f2868  00055d64 <runtime.findrunnable+4748>  00000001 
a52feb48:  00055d80 <runtime.findrunnable+4776>  006f2868  00000001  00000000 
a52feb58:  00000001  00000001  000567ec <runtime.schedule+700>  006f2868 
a52feb68:  00000000  010017a0  00000000  00000000 
a52feb78:  00000000  00000000  00000000  92772590 
runtime: unknown pc 0xb6dedf24
stack: frame={sp:0xa52feb08, fp:0x0} stack=[0xa4aff1a4,0xa52feda4)
a52fea88:  00000000  fde31900  00000000  92772680 
a52fea98:  00000000  fde31900  00000000  92772670 
a52feaa8:  00000000  fde31900  00000000  92772660 
a52feab8:  00000000  fde31900  00000000  92772650 
a52feac8:  00000000  fde31900  00000000  92772640 
a52fead8:  00000000  fde31900  00000000  92772630 
a52feae8:  00000000  00000006  00000109  a3f04080 
a52feaf8:  a3f0408c  a52feb8c  b6fc0968  b6dedea8 
a52feb08: <00000000  00000000  00000000  92772600 
a52feb18:  00000000  fde31900  00000000  000555c8 <runtime.findrunnable+2800> 
a52feb28:  01028060  00000000  00000000  927725e0 
a52feb38:  00055d50 <runtime.findrunnable+4728>  006f2868  00055d64 <runtime.findrunnable+4748>  00000001 
a52feb48:  00055d80 <runtime.findrunnable+4776>  006f2868  00000001  00000000 
a52feb58:  00000001  00000001  000567ec <runtime.schedule+700>  006f2868 
a52feb68:  00000000  010017a0  00000000  00000000 
a52feb78:  00000000  00000000  00000000  92772590
```

Is this related to the bindings? To me (noob) it does look like an issue with libVLC itself. If so i can open in their repo.

**Comment by adrg** [comment]
Hi @masseelch. I cannot be sure. Can you attach a minimal sample that reproduces the issue so I can check?

**Comment by masseelch** [comment]
I try to create one. So far it sometimes works and sometimes does not.

**Comment by masseelch** [comment]
This happens when trying to detach the event on an `EventManager` that belongs to an already released `Player`. There is no way to check if a player is released already. Functions like `Player.Release()` do check if there is a player to be released. Instead of "blindly" passing down the detach request to libVLC it can be considered to check if the `EventManager` is still attached to an unreleased player :thinking:

**Comment by adrg** [comment]
Event managers in the library are designed like the ones in `libVLC`, so they are "detached" from the particular entity they are managing. I don't have information about the player in the event manager. Adding a `Player.IsReleased` method seems like a good idea though. I think I'll add that in the next release of the library.
However, I consider this to be user error because even if `EventManager.Detach` would ignore calls for released entities or return an error, those events would not be detached, so it's still a bug.

In `v4` of this library (which will implement bindings for `libVLC v4`), I will simplify the event management for all the entities. I think will manage all events internally and expose them through callbacks (i.e. event managers would not be exported anymore).

**Comment by masseelch** [comment]
Having multiple routines directly use the player is not the best idea really, so I understand your concerns. It is indeed an user error.

Should I leave this open as reminder for the `Player.IsReleased()` method?

**Comment by adrg** [comment]
That's not necessary. I already added a note in my TODO list regarding this.
