### ISSUE TITLE
[bug] MediaPlayerEndReached Event not thrown reliably

### ISSUE THREAD

**Issue by masseelch** [adrg/libvlc-go#78]
I am playing several videos after another in a loop. One of the videos is [this one](https://file.io/By87wFkNjU25). After a while my video loop hangs because the `EventManager` does not receive the `MediaPlayerEndReached` even though the video has ended. 

I do not know how to reproduce this issue but it does only happen to the linked video. Several others I tested work fine.

**Comment by masseelch** [comment]
Another think I noticed on this specific video: `ParseWithOptions` does never sent any `vlc.MediaParsedChanged` events.

**Comment by adrg** [comment]
Hi @masseelch. Sorry for the late response. I cannot reproduce the issue you are having with the video you mentioned.
Both events are firing for me when using the [player](https://github.com/adrg/libvlc-go-examples/blob/master/v3/player/player.go) and [media information](https://github.com/adrg/libvlc-go-examples/blob/master/v3/media_information/media_information.go) examples with that video.

Does the issue reproduce for you using these examples?

**Comment by masseelch** [comment]
Yes, the issue reproduces with that examples. The videos are running on a RPI 4, 4GB.

**Comment by masseelch** [comment]
I am not able to reliably run vlc. I have even switched the hardware completely. 

I am now doing it with omxplayer.
