### ISSUE TITLE
go get Error: How to solve this problem

### ISSUE THREAD

**Issue by jonbastk** [adrg/libvlc-go#79]
# github.com/adrg/libvlc-go/v3
../../pkg/mod/github.com/adrg/libvlc-go/v3@v3.1.4/av.go:4:11: fatal error: 'vlc/vlc.h' file not found
 #include <vlc/vlc.h>
          ^~~~~~~~~~~
1 error generated.

**Comment by xiongchaoks** [comment]
The test case cannot run

**Comment by adrg** [comment]
Hi @jonbastk. Can you provide more information about the issue, like the operating system you are using? It looks like you haven't installed the `libvlc` development files. Please take a look at the [prerequisites](https://github.com/adrg/libvlc-go#prerequisites) section in the README.

**Comment by adrg** [comment]
Closing this issue as it has been addressed. Please reopen if there are any issues with the provided solution.
