### ISSUE TITLE
could not initialize module in macos

### ISSUE THREAD

**Issue by zeus100** [adrg/libvlc-go#86]
1.  install vlc according to this guide https://github.com/adrg/libvlc-go/wiki/Install-on-macOS
2. error ”could not initialize module“ occurred when run sample code 
if err := vlc.Init("--no-video", "--quiet"); err != nil {
		log.Fatal(err)
	})

**Comment by adrg** [comment]
Hi @zeus100. Thank you for your interest in the library.

Could you provide more details about your environment and how you installed `libVLC`? What version of macOS are you on? Where are the `libVLC` SDK files located? Does the `VLC_PLUGIN_PATH` environment variable contain the correct path?

What is the output if you initialize the module like this? Please post it here.
```go
if err := vlc.Init("--no-video", "-vvv"); err != nil {
	log.Fatal(err)
}
```

**Comment by zeus100** [comment]
@adrg thank you for your library and your advice
my work environment  is Mac mini (2018) with macOS Monterey (12.0.1), install libvlc with MacPorts, according to this file https://github.com/adrg/libvlc-go/wiki/Install-on-macOS .

libvlc location and VLC_PLUGIN_PATH information like this:
zeus@192 ~ % port contents vlc |grep include |head -n 10
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/deprecated.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_dialog.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_events.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_discoverer.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_library.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_list.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_list_player.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_player.h
zeus@192 ~ % port contents vlc |grep lib |head -n 10
  /Applications/MacPorts/VLC.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/breakpadUtilities.dylib
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_dialog.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_events.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_discoverer.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_library.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_list.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_list_player.h
  /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc/libvlc_media_player.h
zeus@192 ~ % export |grep VLC_PLUGIN_PATH
VLC_PLUGIN_PATH=/Applications/MacPorts/VLC.app/Contents/MacOS

`if err := vlc.Init("--no-video", "-vvv"); err != nil {
	log.Fatal(err)
}
error information: 2022/01/02 11:08:30 could not initialize module
`


> Hi @zeus100. Thank you for your interest in the library.
> 
> Could you provide more details about your environment and how you installed `libVLC`? What version of macOS are you on? Where are the `libVLC` SDK files located? Does the `VLC_PLUGIN_PATH` environment variable contain the correct path?
> 
> What is the output if you initialize the module like this? Please post it here.
> 
> ```go
> if err := vlc.Init("--no-video", "-vvv"); err != nil {
> 	log.Fatal(err)
> }
> ```

**Comment by adrg** [comment]
I see. Did you also do this part?
```bash
sudo ln -s /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc /usr/local/include/
sudo ln -s /Applications/MacPorts/VLC.app/Contents/MacOS/lib/* /usr/local/lib/
```

Do you have the `libVLC` libraries in `/usr/local/lib/`? Post a `ls` of that if you can please.

**Comment by zeus100** [comment]
yes, also do ln -s action.

`
zeus@192 ~ % ls /usr/local/lib
docker			libvlc.dylib		libvlccore.dylib
libvlc.5.dylib		libvlccore.9.dylib

zeus@192 ~ % ls /usr/local/include
vlc

zeus@192 ~ % cd /usr/local/include
zeus@192 include % ls -al
total 0
drwxrwxrwx   4 zeus  admin  128 12 31 10:54 .
drwxr-xr-x  18 root  wheel  576 11  6 17:09 ..
-rw-r--r--   1 zeus  admin    0 11 14  2020 .keepme
lrwxr-xr-x   1 root  admin   57 12 31 10:54 vlc -> /Applications/MacPorts/VLC.app/Contents/MacOS/include/vlc

zeus@192 ~ % ls /usr/local/include/vlc |head -n 10
deprecated.h
libvlc.h
libvlc_dialog.h
libvlc_events.h
libvlc_media.h
libvlc_media_discoverer.h
libvlc_media_library.h
libvlc_media_list.h
libvlc_media_list_player.h
libvlc_media_player.h
`

**Comment by adrg** [comment]
Hm, everything seems to be correct. Could you post the output of `go env` as well?

**Comment by zeus100** [comment]
sorry for late, working day is so busy.
my go env info:
zeus@192 ~ % go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zeus/Library/Caches/go-build"
GOENV="/Users/zeus/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zeus/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zeus/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3z/8b0vkhgx2rz89m5vcl7chd280000gn/T/go-build919266373=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by adrg** [comment]
I don't see any problems here either. Not really sure what the issue is. 

Could you save this small C sample in a file called `sample.c`? 
```C
#include <stdio.h>
#include <vlc/vlc.h>

int main(int argc, char* argv[]) {
    libvlc_instance_t* inst = libvlc_new(0, NULL);
    if (inst != NULL) {
        libvlc_release(inst);
    } else {
        printf("libVLC instance is NULL.\n");
    }
}
```

Then try to compile it and run it using:
```bash
clang -o sample sample.c -lvlc
./sample
```
Does that work?

Perhaps try creating symlinks of the `libvlc` libraries in `/usr/lib` as well, or just copy the libraries from `/Applications/MacPorts/VLC.app/Contents/MacOS/lib/` there.
```bash
sudo ln -s /Applications/MacPorts/VLC.app/Contents/MacOS/lib/* /usr/lib/
```

**Comment by zeus100** [comment]
The c code also dose not work, and can't create symlinks to /usr/lib/ (Operation not permitted)
zeus@192 work % cat vlc.c
#include <stdio.h>
#include <vlc/vlc.h>

int main(int argc, char* argv[]) {
    libvlc_instance_t* inst = libvlc_new(0, NULL);
    if (inst != NULL) {
        printf("libVLC instance created.\n");
        libvlc_release(inst);
    }
}
zeus@192 work % clang -o sample vlc.c -l vlc
zeus@192 work % chmod 777 sample
zeus@192 work % ./sample
zeus@192 work %

**Comment by zeus100** [comment]
Maybe I  know what's the cause of the problem, the libvlc.dylib path is not correct.

I will try using install_name_tools to reset the libvlc.dylib path 
zeus@192 work % otool -L sample
sample:
	@rpath/libvlc.dylib (compatibility version 12.0.0, current version 12.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)

**Comment by adrg** [comment]
> The c code also dose not work, and can't create symlinks to /usr/lib/ (Operation not permitted)

That's weird. Don't you have root access?

Anyway, so somehow, the library is not found at runtime, but it is found at compile time (when it's linked). What's the output of this?
```bash
echo $LD_LIBRARY_PATH
```

Does it work if you do this?
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```
before running either the C sample or the Go sample?

**Comment by zeus100** [comment]
export VLC_PLUGIN_PATH="/Applications/MacPorts/VLC.app/Contents/MacOS"  and the sample code can work
