### ISSUE TITLE
Problems Running on Manjaro

### ISSUE THREAD

**Issue by SamuelMR98** [adrg/libvlc-go#94]
I have tried to run the **basic player usage** example with no luck. The player won't start reproducing the media I'm asking, the program would just run with no output or error message. I looks like some of the functions do work I can use the `vlc.Version()` and the `player.IsPlaying()` for example. The  `player.IsPlaying()` returns `false` after executing the `player.Play()` function. 
I'm using the libVLC `version 3.0.18` and I'm using manjaro. 
Help would be appreciated,
Thanks!

**Comment by adrg** [comment]
Hi @SamuelMR98,

Please add the `-vvv` flag when you initialize the library, run the sample and post the output here. Sharing your exact code would be good as well if possible.

```go
if err := vlc.Init("-vvv"); err != nil {
    log.Fatal(err)
}
defer vlc.Release()
```

Also, how did you install `libVLC`?

**Comment by SamuelMR98** [comment]
I get this error 
```[src/libmpg123/layer3.c:INT123_do_layer3():1771] error: part2_3_length (800) too large for available bit count (736)```
I did intalled libVLC using the `pacman` manager.

**Comment by SamuelMR98** [comment]
Thanks setting up that flag helped me a lot getting it running!

**Comment by adrg** [comment]
No problem. Glad to help.
